server:
  port: 8921

spring:
  application:
    name: tp-users

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: club
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    settings:
      web-allow-others: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/